/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'text-wimbledon-green',
    'text-wimbledon-gold',
    'text-wimbledon-charcoal',
    'bg-wimbledon-green',
    'bg-wimbledon-cream',
    'bg-wimbledon-cream-dark',
    'bg-wimbledon-charcoal',
    'border-wimbledon-green',
    'hover:text-wimbledon-green',
    'hover:text-wimbledon-gold',
    'hover:bg-wimbledon-cream-dark',
    'group-hover:text-wimbledon-green',
    'group-hover:text-wimbledon-gold',
    'group-hover:bg-wimbledon-green',
    'group-hover:text-white',
  ],
  theme: {
    extend: {
      colors: {
        wimbledon: {
          green:        '#1B5C2E',
          'green-dark': '#133F20',
          'green-light':'#2A7A40',
          cream:        '#F5F0E6',
          'cream-dark': '#EDE7D9',
          gold:         '#C9A84C',
          'gold-light': '#E2C97E',
          purple:       '#4B2D6E',
          charcoal:     '#1A1A1A',
          'mid-gray':   '#6B7280',
          'light-gray': '#E5E1D8',
          white:        '#FFFFFF',
        },
      },
      fontFamily: {
        serif:   ['"Cormorant Garamond"', 'Georgia', 'serif'],
        display: ['"Playfair Display"',   'Georgia', 'serif'],
        sans:    ['"DM Sans"',            'Helvetica', 'sans-serif'],
        mono:    ['"JetBrains Mono"',     'monospace'],
      },
      fontSize: {
        'display-xl': ['4rem',    { lineHeight: '1.05', letterSpacing: '-0.02em'  }],
        'display-lg': ['3rem',    { lineHeight: '1.1',  letterSpacing: '-0.02em'  }],
        'display-md': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.015em' }],
        'heading-lg': ['1.75rem', { lineHeight: '1.2',  letterSpacing: '-0.01em'  }],
        'heading-md': ['1.375rem',{ lineHeight: '1.3',  letterSpacing: '-0.01em'  }],
        'heading-sm': ['1.125rem',{ lineHeight: '1.35', letterSpacing: '0'        }],
        'body-lg':    ['1.0625rem',{ lineHeight: '1.7', letterSpacing: '0'        }],
        'body':       ['0.9375rem',{ lineHeight: '1.65',letterSpacing: '0'        }],
        'body-sm':    ['0.8125rem',{ lineHeight: '1.6', letterSpacing: '0'        }],
        'label':      ['0.75rem', { lineHeight: '1',    letterSpacing: '0.08em'   }],
        'label-lg':   ['0.8125rem',{ lineHeight: '1',   letterSpacing: '0.06em'   }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
      },
      borderRadius: {
        'xs':  '2px',
        'sm':  '4px',
        DEFAULT: '6px',
        'md':  '8px',
        'lg':  '12px',
        'xl':  '16px',
        '2xl': '24px',
      },
      boxShadow: {
        'card':       '0 1px 3px rgba(26,26,26,0.06), 0 1px 2px rgba(26,26,26,0.04)',
        'card-hover': '0 4px 12px rgba(26,26,26,0.10), 0 2px 4px rgba(26,26,26,0.06)',
        'nav':        '0 1px 0 rgba(26,26,26,0.08)',
        'dropdown':   '0 8px 24px rgba(26,26,26,0.12), 0 2px 8px rgba(26,26,26,0.08)',
      },
      keyframes: {
        'fade-in':    { '0%': { opacity: '0', transform: 'translateY(6px)'  }, '100%': { opacity: '1', transform: 'translateY(0)'  } },
        'slide-down': { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)'  } },
      },
      animation: {
        'fade-in':    'fade-in 0.35s ease forwards',
        'slide-down': 'slide-down 0.25s ease forwards',
      },
    },
  },
  plugins: [],
}
